version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: investguru
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8100:8100"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app

  worker:
    build: ./backend
    command: ["python", "worker.py"]
    env_file: ./backend/.env
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./backend:/app

  web:
    build: ./frontend
    env_file: ./frontend/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pg_data:
